server:
  servlet:
    contextPath: /scrabble
spring.jackson.serialization.WRITE_NULL_MAP_VALUES: false
spring.jackson.default-property-inclusion: non_empty

logging:
  level:
    root: INFO
    com.gammel.conan.scrabble: DEBUG